// Shared inline style constants — import as: import { S } from '../styles/shared'
export const S = {
  btnPrimary: {
    padding: '7px 14px',
    background: 'var(--primary)',
    color: '#fff',
    border: 'none',
    borderRadius: 7,
    fontWeight: 700,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  btnSecondary: {
    padding: '7px 14px',
    background: 'var(--surface)',
    color: 'var(--text)',
    border: '1px solid var(--border)',
    borderRadius: 7,
    fontWeight: 600,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  btnDanger: {
    padding: '7px 14px',
    background: 'none',
    color: 'var(--warning)',
    border: '1px solid var(--warning)',
    borderRadius: 7,
    fontWeight: 600,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  th: {
    padding: '10px 14px',
    textAlign: 'left',
    fontSize: 12,
    fontFamily: 'var(--font-condensed)',
    fontWeight: 500,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  td: {
    padding: '10px 14px',
    textAlign: 'left',
    fontSize: 13,
  },
  input: {
    padding: '8px 10px',
    border: '1.5px solid var(--border)',
    borderRadius: 7,
    fontSize: 13,
    outline: 'none',
    background: 'var(--surface)',
    width: '100%',
    fontFamily: 'inherit',
  },
  label: {
    fontSize: 12,
    fontWeight: 500,
    color: 'var(--text-secondary)',
    display: 'block',
    marginBottom: 4,
  },
  modalSm: {
    background: 'var(--surface-elevated)',
    borderRadius: 12,
    padding: 28,
    maxWidth: 400,
    width: '100%',
  },
  modalLg: {
    background: 'var(--surface-elevated)',
    borderRadius: 12,
    padding: 28,
    width: 480,
    maxWidth: '100%',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: 16,
  },
  errorBanner: {
    background: '#fff5f5',
    border: '1px solid #f5c6c6',
    borderRadius: 6,
    padding: '10px 14px',
    marginBottom: 16,
    fontSize: 13,
    color: 'var(--warning)',
  },
}
